### ISSUE TITLE
Drawing canvas

### ISSUE THREAD

**Issue by Vuurvos1** [Vuurvos1/drawingGame#11]
- [x] Flood fill / bucket
- [x] Color
- [x] Brush size
- [x] Erasor
- [x] Undo
- [x] Save

### Sockets
- [x] Strokes
- [x] Erasor
- [x] Flood fill
- [x] Undo

Maybe some other nice to haves?

**Comment by Vuurvos1** [comment]
See branch [feature/canvas](https://github.com/Vuurvos1/multiplayerGame/tree/feature/canvas)

**Comment by Vuurvos1** [comment]
@RowinRuizendaal this is basically done, we can move the save option to a new "nice to have" with low priority issue

**Comment by RowinRuizendaal** [comment]
@Vuurvos1 Yes I agree, these were top priority since it is the core functionality of the game.

Set the save functionality to low priority with a explanation etc.

**Comment by RowinRuizendaal** [comment]
https://github.com/Vuurvos1/drawingGame/issues/23
