### ISSUE TITLE
Chatting

### ISSUE THREAD

**Issue by Vuurvos1** [Vuurvos1/drawingGame#12]
Create the ability to send messages in real-time to each other inside a socket room

**Comment by RowinRuizendaal** [comment]
@Vuurvos1 

I think the core functionality of the game is to guess the word and not a chatting app, so what do you mean by chatting

**Comment by Vuurvos1** [comment]
I think being able to send and receive messages and guesses from others gives a better sense of playing with and against other people, even when not together or in a voice call for example. The chat will mainly be used for guessing the drawings but I don't think it would be much more work to have it also show messages from other people playing

**Comment by RowinRuizendaal** [comment]
@Vuurvos1 

https://github.com/Vuurvos1/drawingGame/tree/feature/chat

Working chat functionality, the names seem to be buggy as I mentioned before
