### ISSUE TITLE
Multi Language support

### ISSUE THREAD

**Issue by Vuurvos1** [Vuurvos1/drawingGame#18]
Give players the ability to play with words from a different language

**Comment by RowinRuizendaal** [comment]
I assume this will be English and Dutch or?

**Comment by Vuurvos1** [comment]
Yea, and maybe more...

**Comment by RowinRuizendaal** [comment]
https://www.npmjs.com/package/svelte-i18n

**Comment by Vuurvos1** [comment]
I don't know if I want to translate the entire word list myself, lol

**Comment by RowinRuizendaal** [comment]
Decided to just have translations for the UI right now
