### ISSUE TITLE
Alles designer

### ISSUE THREAD

**Issue by Vuurvos1** [Vuurvos1/drawingGame#26]
Create designs for the app for a better user experience

**Comment by RowinRuizendaal** [comment]
@Vuurvos1,

Lets make a design by our self and show them to eachother to combine both ideas into one

**Comment by RowinRuizendaal** [comment]
@Vuurvos1,

Issue is still relevant? Or can this one be closed?

**Comment by Vuurvos1** [comment]
This can be closed, most of the design is done. Small tweaks and additions can be included in other merge requests
