### ISSUE TITLE
Replace grid-columns to be more responsive on bigger screens

### ISSUE THREAD

**Issue by RowinRuizendaal** [Vuurvos1/drawingGame#47]
Currently, the grid on wide screens looks like this:

![image](https://user-images.githubusercontent.com/33514521/143554207-224cd931-88f9-460c-988a-a6c711599af9.png)

there is an easy fix to make this better:

```CSS
grid-template-columns: repeat(3, 1fr);
```

**Comment by Vuurvos1** [comment]
I'm not sure if `fr` would be best here since not every column is 1 fraction, it would probably be better to have a more fixed chat and user list width and then scale the canvas, and for really small screens I don't know what the best layout would be

**Comment by RowinRuizendaal** [comment]
Well, I think it doesn't matter since we are refactoring the whole UI, I just suggested it as a quick fix which seems way better on a bigger screen and smaller screen.
